# saas前端项目的gitlab-ci的模板文件

stages:
  - Build
  - deploy
before_script:
  - PROD_VERSION_HUBEI=`cat project_version/hubei_version`
  - PROD_VERSION_HUBEI_BOC=`cat project_version/boc_hubei_version`
  - PROD_VERSION_CMB_WUHAN=`cat project_version/cmb_wuhan_version`
  
variables:
  ALIYUN_REGISTRY: registry-vpc.cn-hangzhou.aliyuncs.com
  REGISTRY_NAME_SPECE: ybt_service
  IMAGE_FULL_NAME: $ALIYUN_REGISTRY/$REGISTRY_NAME_SPECE/$CI_PROJECT_NAME
  main_project_name: Saas
  oss_path: oss://ycb51-bucket/frontend/$main_project_name/$CI_PROJECT_NAME/
  uat_oss_path: oss://ycb51-bucket/frontend/Saas_uat/$CI_PROJECT_NAME/


#################################################k8s-test##########################################################
Build k8s-test:
  stage: Build
  script:
    - cnpm i
    - cnpm run build
    - tar zcf $CI_PROJECT_NAME.tar.gz.dev dist
    - docker build -t $IMAGE_FULL_NAME:dev .
    - docker push $IMAGE_FULL_NAME:dev
    - echo $IMAGE_FULL_NAME:dev
  only:
    refs:
      - test
  except:
    changes:
      - .gitlab-ci.yml
  tags:
    - ci

  
# 部署k8s-测试环境
Deploy k8s-test:
  stage: deploy
  script:
    - helm uninstall supply-page -n saas-dev
    - helm upgrade -i supply-page /root/helm_repo/saas/supply-page -n saas-dev -f /root/helm_repo/saas/supply-page/values-dev.yaml --wait --timeout 3m30s
  only:
    refs:
      - test
  tags:
    - kube-master1-test
  except:
    changes:
      - .gitlab-ci.yml

# 部署uat环境
Build uat:
  stage: Build
  script:
    - cnpm i
    - cnpm run build
    - tar zcf $CI_PROJECT_NAME.tar.gz.uat dist
    - docker build -t $IMAGE_FULL_NAME:uat .
    - docker push $IMAGE_FULL_NAME:uat
    - echo $IMAGE_FULL_NAME:uat

  only:
    refs:
      - uat
  except:
    changes:
      - .gitlab-ci.yml
  tags:
    - ci


Deploy uat:
  stage: deploy
  script:
    - helm uninstall supply-page-u -n saas-prod
    - helm upgrade -i supply-page-u /root/helm_repo/saas/supply-page -n saas-prod -f /root/helm_repo/saas/supply-page/values-uat.yaml --wait --timeout 1m30s
  tags:
    - kube-master1-test
  only:
    refs:
      - uat
  except:
    changes:
      - .gitlab-ci.yml


Build prod:
  stage: Build
  script:
    - cnpm i
    - cnpm run build
    - tar zcf $CI_PROJECT_NAME.tar.gz.v1.0.2 dist
    - docker build -t $IMAGE_FULL_NAME:v1.0.2 .
    - docker push $IMAGE_FULL_NAME:v1.0.2
    - echo $IMAGE_FULL_NAME:v1.0.2
  tags:
    - ci
  only:
    refs:
      - master
  except:
    changes:
      - .gitlab-ci.yml
  
Deploy pord:
  stage: deploy
  script:
    - helm uninstall supply-page -n saas-prod
    - helm upgrade -i supply-page /root/helm_repo/saas/supply-page -n saas-prod -f /root/helm_repo/saas/supply-page/values-prod.yaml --wait --timeout 1m30s
  tags:
    - kube-master1-test
  only:
    refs:
      - master
  except:
    changes:
      - .gitlab-ci.yml
